version: "3.9"
volumes:
  media_data:
    driver: local
    driver_opts:
      o: bind
      device: /koala/volumes/media_data
      type: none
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4200:3333"
    container_name: api
    volumes:
       - ./api:/usr/src/app/api
       - media_data:${MEDIA_DATA_PATH}
  frontend:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    ports:
      - "8888:80"
    container_name: koala-frontend
    volumes:
       - ./app-ui:/usr/src/app/app-ui
