version: "3.9"
volumes:
  media_data:
    driver: local
    driver_opts:
      o: bind
      device: /koala/data/media_volume
      type: none
  database:
    driver: local
    driver_opts:
      o: bind
      device: /koala/data/database
      type: none
services:
  api:
    image: ghcr.io/koala-mhf/koala-app-api:${IMAGE_TAG}
    user: "1000:1024"
    ports:
      - "4200:3333"
    container_name: api
    volumes:
      #- ./api:/usr/src/app/api
      - media_data:${MEDIA_DATA_PATH}
      - database:/usr/src/app
  frontend:
    image: ghcr.io/koala-mhf/koala-app-frontend:${IMAGE_TAG}
    ports:
      - "8888:80"
    container_name: koala-frontend
    volumes:
      - ./app-ui:/usr/src/app/app-ui
