version: "3.9"
services:
  api:
    build:
      context: ./koala-app
      dockerfile: Dockerfile
    ports:
      - "4200:3333"
    container_name: api
    volumes:
       - ./api:/usr/src/app/api
  frontend:
    build:
      context: ./koala-app
      dockerfile: frontend.Dockerfile
    ports:
      - "8888:80"
    container_name: koala-frontend
    volumes:
       - ./app-ui:/usr/src/app/app-ui
